/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team1.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void test() {
        //fail("Not yet implemented");
 
    }
}
